# Generated by Django 6.0.4 on 2026-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='avg_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='courses_offered',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='college',
            name='exam_accepted',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='ownership',
            field=models.CharField(default='Private', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='college',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='college',
            name='reviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
