import os
import sys
import django

# Setup Django
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from colleges.models import College

# Comprehensive college data with all required fields
colleges_data = [
    {
        "name": "Indian Institute of Technology Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "course": "B.Tech Computer Science",
        "description": "IIT Delhi is one of the premier engineering institutions in India with excellent placement records and world-class research facilities.",
        "fees": 220000,
        "rating": 4.8,
        "placement_percentage": 98.5,
        "avg_salary": 2500000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Amit S.", "rating": 5, "comment": "Excellent placement opportunities!"}, {"user": "Priya M.", "rating": 4, "comment": "Great faculty and infrastructure."}],
        "image_url": "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
        "established_year": 1961,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Indian Institute of Technology Bombay",
        "city": "Mumbai",
        "state": "Maharashtra",
        "course": "B.Tech Computer Science",
        "description": "IIT Bombay is the oldest IIT in Asia with exceptional academic standards and industry connections.",
        "fees": 210000,
        "rating": 4.9,
        "placement_percentage": 99.2,
        "avg_salary": 2800000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Rahul K.", "rating": 5, "comment": "Best engineering college in India!"}, {"user": "Sneha J.", "rating": 5, "comment": "Amazing campus life and placements."}],
        "image_url": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
        "established_year": 1958,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Indian Institute of Technology Madras",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "IIT Madras is known for its excellent research output and strong industry connections in South India.",
        "fees": 210000,
        "rating": 4.8,
        "placement_percentage": 98.8,
        "avg_salary": 2600000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Vijay P.", "rating": 5, "comment": "Great research opportunities!"}, {"user": "Anjali R.", "rating": 4, "comment": "Beautiful campus and supportive faculty."}],
        "image_url": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
        "established_year": 1959,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Indian Institute of Technology Kanpur",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "course": "B.Tech Computer Science",
        "description": "IIT Kanpur is known for its strong emphasis on research and innovation in engineering sciences.",
        "fees": 200000,
        "rating": 4.7,
        "placement_percentage": 97.5,
        "avg_salary": 2400000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Deepak T.", "rating": 4, "comment": "Excellent research culture."}, {"user": "Meera S.", "rating": 5, "comment": "Great faculty and peer group."}],
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
        "established_year": 1959,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Indian Institute of Technology Kharagpur",
        "city": "Kharagpur",
        "state": "West Bengal",
        "course": "B.Tech Computer Science",
        "description": "IIT Kharagpur is the first IIT established in India with the largest campus and diverse programs.",
        "fees": 200000,
        "rating": 4.7,
        "placement_percentage": 97.8,
        "avg_salary": 2350000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Sourav D.", "rating": 5, "comment": "Oldest and most prestigious IIT!"}, {"user": "Kavya N.", "rating": 4, "comment": "Vibrant campus life."}],
        "image_url": "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=400",
        "established_year": 1951,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Birla Institute of Technology and Science Pilani",
        "city": "Pilani",
        "state": "Rajasthan",
        "course": "B.Tech Computer Science",
        "description": "BITS Pilani is a premier private engineering university known for its rigorous academics and placements.",
        "fees": 450000,
        "rating": 4.6,
        "placement_percentage": 96.5,
        "avg_salary": 2200000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech Chemical", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Arjun M.", "rating": 4, "comment": "Great placements and industry interface."}, {"user": "Divya L.", "rating": 5, "comment": "Excellent peer learning environment."}],
        "image_url": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400",
        "established_year": 1964,
        "exam_accepted": ["BITSAT", "JEE Advanced"],
        "ownership": "Private"
    },
    {
        "name": "Vellore Institute of Technology",
        "city": "Vellore",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "VIT is one of the largest private engineering universities in India with excellent infrastructure and placements.",
        "fees": 350000,
        "rating": 4.5,
        "placement_percentage": 95.8,
        "avg_salary": 1800000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Karthik R.", "rating": 4, "comment": "Good placements and modern campus."}, {"user": "Shruti K.", "rating": 5, "comment": "Excellent infrastructure and facilities."}],
        "image_url": "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
        "established_year": 1984,
        "exam_accepted": ["VITEEE", "JEE Main"],
        "ownership": "Private"
    },
    {
        "name": "National Institute of Technology Trichy",
        "city": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "NIT Trichy is one of the top NITs in India with excellent academics and placement records.",
        "fees": 150000,
        "rating": 4.4,
        "placement_percentage": 94.2,
        "avg_salary": 1600000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Prashant S.", "rating": 4, "comment": "Good placement opportunities."}, {"user": "Nisha P.", "rating": 4, "comment": "Quality education at affordable cost."}],
        "image_url": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
        "established_year": 1964,
        "exam_accepted": ["JEE Main"],
        "ownership": "Government"
    },
    {
        "name": "Indian Institute of Technology Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "B.Tech Computer Science",
        "description": "IIT Hyderabad is a newer IIT with strong focus on research and innovation in emerging technologies.",
        "fees": 200000,
        "rating": 4.5,
        "placement_percentage": 96.8,
        "avg_salary": 2300000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Harsha V.", "rating": 5, "comment": "Great research opportunities in AI/ML."}, {"user": "Riya C.", "rating": 4, "comment": "Excellent faculty and labs."}],
        "image_url": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
        "established_year": 2008,
        "exam_accepted": ["JEE Advanced", "GATE"],
        "ownership": "Government"
    },
    {
        "name": "Delhi Technological University",
        "city": "New Delhi",
        "state": "Delhi",
        "course": "B.Tech Computer Science",
        "description": "DTU is a leading technical university in Delhi with excellent placement records and industry connections.",
        "fees": 180000,
        "rating": 4.3,
        "placement_percentage": 93.5,
        "avg_salary": 1500000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA"],
        "reviews": [{"user": "Vikram B.", "rating": 4, "comment": "Good placements in top companies."}, {"user": "Aisha K.", "rating": 4, "comment": "Located in the heart of Delhi."}],
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
        "established_year": 1941,
        "exam_accepted": ["JEE Main", "DTU CET"],
        "ownership": "Government"
    },
    {
        "name": "Thapar Institute of Engineering and Technology",
        "city": "Patiala",
        "state": "Punjab",
        "course": "B.Tech Computer Science",
        "description": "Thapar University is a premier private engineering college in North India with excellent placements.",
        "fees": 380000,
        "rating": 4.4,
        "placement_percentage": 94.8,
        "avg_salary": 1700000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Gurpreet S.", "rating": 4, "comment": "Excellent placement record."}, {"user": "Tanya M.", "rating": 5, "comment": "Great infrastructure and faculty."}],
        "image_url": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400",
        "established_year": 1956,
        "exam_accepted": ["JEE Main", "Thapar JEE"],
        "ownership": "Private"
    },
    {
        "name": "Manipal Academy of Higher Education",
        "city": "Manipal",
        "state": "Karnataka",
        "course": "B.Tech Computer Science",
        "description": "MAHE is a premier private university in Karnataka known for its quality engineering education.",
        "fees": 400000,
        "rating": 4.3,
        "placement_percentage": 93.2,
        "avg_salary": 1650000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "MBBS"],
        "reviews": [{"user": "Aditya R.", "rating": 4, "comment": "Good campus and placements."}, {"user": "Sonal J.", "rating": 4, "comment": "Beautiful location and infrastructure."}],
        "image_url": "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=400",
        "established_year": 1953,
        "exam_accepted": ["MET", "JEE Main"],
        "ownership": "Private"
    },
    {
        "name": "College of Engineering Guindy",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "CEG is one of the oldest engineering colleges in Asia with excellent academic heritage.",
        "fees": 80000,
        "rating": 4.5,
        "placement_percentage": 95.5,
        "avg_salary": 1800000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Kavin P.", "rating": 5, "comment": "Oldest engineering college in Asia!"}, {"user": "Lakshmi S.", "rating": 4, "comment": "Great alumni network."}],
        "image_url": "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
        "established_year": 1794,
        "exam_accepted": ["TNEA", "JEE Main"],
        "ownership": "Government"
    },
    {
        "name": "Jadavpur University",
        "city": "Kolkata",
        "state": "West Bengal",
        "course": "B.Tech Computer Science",
        "description": "Jadavpur University is a premier technical university in Eastern India with excellent research output.",
        "fees": 12000,
        "rating": 4.4,
        "placement_percentage": 94.0,
        "avg_salary": 1550000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "PhD"],
        "reviews": [{"user": "Sayan D.", "rating": 4, "comment": "Excellent research opportunities."}, {"user": "Ankita M.", "rating": 5, "comment": "Affordable quality education."}],
        "image_url": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400",
        "established_year": 1955,
        "exam_accepted": ["WBJEE", "JEE Main"],
        "ownership": "Government"
    },
    {
        "name": "Amrita Vishwa Vidyapeetham",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "Amrita is a multi-university with campuses across India known for research in AI and sustainability.",
        "fees": 360000,
        "rating": 4.5,
        "placement_percentage": 95.2,
        "avg_salary": 1750000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech AI", "M.Tech", "PhD"],
        "reviews": [{"user": "Madhavan K.", "rating": 5, "comment": "Excellent focus on research."}, {"user": "Pooja R.", "rating": 4, "comment": "Great campus and facilities."}],
        "image_url": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400",
        "established_year": 2003,
        "exam_accepted": ["AEEE", "JEE Main"],
        "ownership": "Private"
    },
    {
        "name": "SRM Institute of Science and Technology",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech Computer Science",
        "description": "SRM is one of the largest private engineering universities in India with multiple campuses.",
        "fees": 450000,
        "rating": 4.2,
        "placement_percentage": 92.5,
        "avg_salary": 1450000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Harish V.", "rating": 4, "comment": "Good infrastructure and placements."}, {"user": "Divya S.", "rating": 4, "comment": "Multiple campus options."}],
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
        "established_year": 1985,
        "exam_accepted": ["SRMJEEE", "JEE Main"],
        "ownership": "Private"
    },
    {
        "name": "Lovely Professional University",
        "city": "Phagwara",
        "state": "Punjab",
        "course": "B.Tech Computer Science",
        "description": "LPU is one of the largest private universities in India with diverse programs and excellent placements.",
        "fees": 320000,
        "rating": 4.1,
        "placement_percentage": 91.8,
        "avg_salary": 1350000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "B.Tech CE", "M.Tech", "MBA", "PhD"],
        "reviews": [{"user": "Rajiv M.", "rating": 4, "comment": "Great placement opportunities."}, {"user": "Neha P.", "rating": 4, "comment": "Modern infrastructure."}],
        "image_url": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400",
        "established_year": 2005,
        "exam_accepted": ["LPUNEST", "JEE Main"],
        "ownership": "Private"
    },
    {
        "name": "Jamia Millia Islamia",
        "city": "New Delhi",
        "state": "Delhi",
        "course": "B.Tech Computer Science",
        "description": "JMI is a central university with excellent academic reputation and affordable education.",
        "fees": 25000,
        "rating": 4.3,
        "placement_percentage": 93.0,
        "avg_salary": 1400000,
        "courses_offered": ["B.Tech CSE", "B.Tech ECE", "B.Tech ME", "M.Tech", "PhD"],
        "reviews": [{"user": "Saif A.", "rating": 4, "comment": "Affordable quality education."}, {"user": "Zara K.", "rating": 5, "comment": "Excellent faculty and location."}],
        "image_url": "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=400",
        "established_year": 1920,
        "exam_accepted": ["JMI Entrance", "JEE Main"],
        "ownership": "Government"
    },
    {
        "name": "University of Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "M.Tech Computer Science",
        "description": "UoH is a premier central university known for excellent research in computer science.",
        "fees": 15000,
        "rating": 4.4,
        "placement_percentage": 94.5,
        "avg_salary": 1600000,
        "courses_offered": ["M.Tech CSE", "M.Tech AI", "M.Sc", "PhD"],
        "reviews": [{"user": "Ravi T.", "rating": 5, "comment": "Excellent research opportunities."}, {"user": "Swathi L.", "rating": 4, "comment": "Great faculty and campus."}],
        "image_url": "https://images.unsplash.com/photo-1562774053-701939374585?w=400",
        "established_year": 1974,
        "exam_accepted": ["GATE", "PG Entrance"],
        "ownership": "Government"
    }
]

# Clear existing colleges and add new ones
College.objects.all().delete()

added = 0
for college_data in colleges_data:
    College.objects.create(**college_data)
    added += 1
    print(f"✓ Added: {college_data['name']}")

print(f"\n✓ Successfully added {added} colleges to the database!")
print(f"Total colleges in database: {College.objects.count()}")